[package]
name = "rsd_raytracer"
version = "0.1.0"
authors = ["Kildyushkin_Dmitriy <kild-dima@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.10"
clap = "3.0.0-beta.2"